# A/B Tests Configuration File
# Edit this file, and the GitHub Action will generate config.json

experiments:
    
featureFlags:
  - name: "promo_codes_in_onboarding_paywall"
    enabled: false
  - name: "feature_not_exists"
    enabled: false
