# A/B Tests Configuration File
# Edit this file, and the GitHub Action will generate config.json

experiments:
  - id: "experiment20251008paywallFromSheet"
    enabled: true
    rollout_percent: 100
  - id: "experiment20250908sensoryFeedbackInOnboarding"
    enabled: false
  - id: "new_checkout_flow"
    enabled: true
    rollout_percent: 10
    
featureFlags:
  - name: "promo_codes_in_onboarding_paywall"
    enabled: false
  - name: "feature_not_exists"
    enabled: false
