# A/B Tests and feature flags Configuration File
# Edit this file, and the GitHub Action will generate config.json

#Example:

#experiments:
#  - id: "experiment20251008paywallFromSheet"
#    enabled: true
#    rollout_percent: 100
#featureFlags:
#  - name: "promo_codes_in_onboarding_paywall"
#    enabled: false

#Make sure experiments and featureFlags both have items or are defined as [] 
experiments: []
featureFlags: []
