# A/B Tests Configuration File
# Edit this file, and the GitHub Action will generate config.json

experiments:
  - id: "new_feature_onboarding"
    enabled: true
    rollout_percent: 50
  - id: "redesigned_homescreen"
    enabled: false
  - id: "new_checkout_flow"
    enabled: true
    rollout_percent: 10

featureFlags:
  - name: "offer_codes_in_onboarding_paywall"
    enabled: true
  
