name: Generate, Validate, and Deploy A/B Test Config to Pages

on:
  push:
    branches:
      - main
    paths:
      - 'config.yaml' # Only run this workflow when config.yaml changes

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository code
      - name: Checkout Repo
        uses: actions/checkout@v4

      # 2. Convert YAML to JSON and Validate
      - name: Convert YAML to JSON and Validate
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          pip install pyyaml jsonschema
          python -c "import yaml, json, sys; sys.stdout.write(json.dumps(yaml.safe_load(open('config.yaml')), indent=2))" > config.json
          jsonschema -i config.json .github/schemas/schema.json

      # 3. Setup Pages
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      # 4. Prepare artifact
      - name: Prepare artifact
        run: mkdir -p public && mv config.json public/

      # 5. Upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
